/*
    Legacy SWAT vs Terrorists - TDM Game Project for San Andreas: Multiplayer (0.3.7>=)
    Copyright (C) 2020 A.S. "H2O" Ahmed <https://www.h2omultiplayer.com>

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

#if !defined _SVT_CONF
    #define _SVT_CONF
#else
    #endinput
#endif

//General
#define WEBSITE 		            "h2omultiplayer.com"

//MySQL
#define MYSQL_HOST				  	""
#define MYSQL_USER                	""
#define MYSQL_PASSWORD            	""
#define MYSQL_DATABASE            	""

//End of File
/* (c) H2O Multiplayer 2018-2020. All rights reserved. */